# 解决弹窗
- name: 'a_dobe_dumb'
  url: 'https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/list.txt'
  format: 'list'
  processor: |
    CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
    sed -n -e '/# Last update:/p' -e '/^0\.0\.0\.0/s/0\.0\.0\.0 //p' "$TEMP_FILE" > "$PROCESSED_FILE"
    sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"

# 秋风广告规则
- name: 'AWAvenue_Ads_Rule_Clash'
  url: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml'
  format: 'yaml'
  processor: |
    sed "1i\# 原始仓库: https://github.com/TG-Twilight/AWAvenue-Ads-Rule" "$TEMP_FILE" > "$PROCESSED_FILE"

# telegram_domain 规则
- name: 'telegram_domain'
  url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.list'
  format: 'list'
  processor: |
    sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo/geosite" "$TEMP_FILE" > "$PROCESSED_FILE"
