# 自用版本
# 日期：2026-06-19
# 修改自: 深巷有喵的「Surge_CN」配置
# 配置作者：https://github.com/Rabbit-Spec/Surge


[General]
# 日志级别
loglevel = notify

# 显示错误页面
show-error-page-for-reject = true

# 允许 Wi-Fi 访问(局域网共享代理)
allow-wifi-access = false

# 混合网络并发 (开启后可同时利用 Wi-Fi 和蜂窝数据提升速度｜但会增加些许耗电)
all-hybrid = false

# IPv6 支持（默认关闭）
ipv6 = false

# IPv6 VIF（默认禁用）
ipv6-vif = disabled

# 测试超时（秒）
test-timeout = 5

# 直连 TCP 测试 URL
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204

# 代理 TCP 测速 URL
proxy-test-url = http://cp.cloudflare.com/generate_204

# 排除简单主机名
exclude-simple-hostnames = true

# DNS 服务器
dns-server = system, 223.5.5.5, 119.29.29.29
# DoH 服务器（部分机场拥有自己的 DoH 来保证节点解析）
# encrypted-dns-server = 你机场的 DoH
# DNS 劫持（强制接管指定 DNS 的 53 端口请求）
hijack-dns = 8.8.8.8:53, 8.8.4.4:53
# 从 /etc/hosts 读取 DNS 记录
read-etc-hosts = true

# HTTP API & Web 面板（默认关闭）
http-api-web-dashboard = false

# 跳过代理（这些地址/网段不经过代理处理）
skip-proxy = 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 162.14.0.0/16, 211.99.96.0/19, 162.159.192.0/24, 162.159.193.0/24, 162.159.195.0/24, fc00::/7, fe80::/10, localhost, *.local, captive.apple.com, passenger.t3go.cn, *.ccb.com, wxh.wo.cn, *.abcchina.com, *.abcchina.com.cn
# 真实 IP 映射（解决 Fake-IP 模式下部分服务不兼容的问题）
always-real-ip = *.msftncsi.com, *.msftconnecttest.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.battlenet.com.cn, *.battlenet.com, *.blzstatic.cn, *.battle.net, *.turn.twilio.com, *.stun.twilio.com, stun.syncthing.net, stun.*, 127.*.*.*.sslip.io, 127-*-*-*.sslip.io, *.127.*.*.*.sslip.io, *-127-*-*-*.sslip.io, 127.*.*.*.nip.io, 127-*-*-*.nip.io, *.127.*.*.*.nip.io, *-127-*-*-*.nip.io
# 兼容模式(若需要使用Homekit摄像头，可以开启兼容模式，但开启兼容模式会导致一些屏蔽广告的模块失效，请自行取舍)
# compatibility-mode = 5

# GeoIP数据库
geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb
# 禁用 GEOIP 自动更新
disable-geoip-db-auto-update = true

# UDP退回行为（当节点不支持 UDP 时直接拒绝，防止数据泄露）
udp-policy-not-supported-behaviour = reject

[Proxy]

[Proxy Group]

[Rule]