[General]
# 日志级别
loglevel = notify
show-error-page-for-reject = true

# 允许Wi-Fi访问
allow-wifi-access = false

# All Hybrid 网络并发
all-hybrid = false

# IPv6 支持（默认关闭）
ipv6 = false
# IPv6 VIF（默认禁用）
ipv6-vif = disabled

# 测试超时（秒）
test-timeout = 2

# Internet 测试 URL
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
# 代理测速 URL
proxy-test-url = http://latency-test.skk.moe/endpoint
proxy-test-udp = www.apple.com@64.6.64.6

# GeoIP数据库
geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb
# 禁用 GEOIP 自动更新
disable-geoip-db-auto-update = true

# 排除简单主机名
exclude-simple-hostnames = true

# DNS 服务器
dns-server = system
hijack-dns = 8.8.8.8:53, 8.8.4.4:53

# DoH 服务器
# encrypted-dns-server = https://doh.pub/dns-query, https://dns.alidns.com/dns-query

# 当遇到 REJECT 策略时返回错误页
skip-proxy = 127.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 162.14.0.0/16, 211.99.96.0/19, 162.159.192.0/24, 162.159.193.0/24, 162.159.195.0/24, fc00::/7, fe80::/10, localhost, *.local, captive.apple.com, passenger.t3go.cn, *.ccb.com, wxh.wo.cn, *.abcchina.com, *.abcchina.com.cn

# 跳过代理
always-real-ip = *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.battlenet.com.cn, *.battlenet.com, *.blzstatic.cn, *.battle.net

# Always Real IP
udp-policy-not-supported-behaviour = REJECT

# UDP退回行为
allow-hotspot-access = false

[Rule]
FINAL,DIRECT
