DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/private.list,DIRECT              // 私有/局域网
RULE-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/ruleset/private.list,DIRECT,no-resolve       // 局域网 ip 段

DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/category-ai-chat-!cn.list,日本自动 // 非国区 Ai
DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/google.list,手动选择               // google 广义域
DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/telegram.list,手动选择             // telegram
DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/meta.list,手动选择                 // meta 系
DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/category-porn.list,手动选择        // nswf

DOMAIN-SET,https://ruleset.skk.moe/List/domainset/apple_cdn.conf,DIRECT
RULE-SET,https://ruleset.skk.moe/List/non_ip/domestic.conf,DIRECT

DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/geolocation-!cn.list,手动选择 // 非中国兜底
DOMAIN-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/domainset/cn.list,DIRECT // 中国兜底

# ip-cidr
RULE-SET,https://raw.githubusercontent.com/yangtudou/Script/rules/Surge/ruleset/telegram.list,手动选择,no-resolve // telegram ip
GEOIP,CN,DIRECT,no-resolve // 国区 ip 兜底

FINAL,默认选择,dns-failed