#> iphone Stash Private Config 
#  iPhone Stash 自用配置，仅供参考
#  规则主要使用了 geosite & geoip
#  geoip 使用了第三方数据库
#  geosite 受限于 Stash 不支持更改，使用了原版
#>
#> ✍️ 洋 san 芋
#> 🕙 last update：2025-12-02

# 图标使用
icon_url:
  cat: &icon_cat "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Cat.png"
  telegram: &icon_telegram "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png"
  youtube: &icon_youtube "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png"
  google: &icon_google "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png"
  hk: &icon_hk "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png"
  tw: &icon_tw "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Taiwan.png"
  jp: &icon_jp "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png"
  sg: &icon_sg "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png"
  us: &icon_us "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png"
  amytelecom: &icon_amytelecom "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/AmyTelecom.png"
  static: &icon_static "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Static.png"
  final: &icon_final "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Final.png"

mode: rule
log-level: info

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fake-ip-filter:
    - geosite:connectivity-check
    - geosite:private
  nameserver-policy:
    geosite:cn,private: https://dns.alidns.com/dns-query

proxies:
  - name: 💚 全球直连
    type: DIRECT

proxy-providers:
  proxy-providers_name: # 远程代理集,名称不可重复
    interval: 86400
    url: url
    filter: "^(?!.*海外).*"

proxy-groups:
  - &proxy-groups_config
    name: 选择代理
    icon: *icon_cat
    type: select
    proxies:
      - 香港自动
      - 台湾自动
      - 日本自动
      - 美国自动
      - 狮城自动
    interval: 600
    lazy: true

  - !!merge <<: *proxy-groups_config
    name: Telegram
    icon: *icon_telegram

  - !!merge <<: *proxy-groups_config
    name: YouTube
    icon: *icon_youtube

  - !!merge <<: *proxy-groups_config
    name: Google
    icon: *icon_google

    # 基于区域的策略
  - &proxy-groups_url-test_config
    !!merge <<: *proxy-groups_config
    name: 香港自动
    filter: "(?i)(澳门|🇲🇴|港|🇭🇰|hk|hong)"
    icon: *icon_hk
    type: url-test
    proxies: null
    include-all: true

  - !!merge <<: *proxy-groups_url-test_config
    name: 台湾自动
    filter: "(?i)(台|🇹🇼|湾|tw|taiwan)"
    icon: *icon_tw

  - !!merge <<: *proxy-groups_url-test_config
    name: 日本自动
    filter: "(?i)(日|🇯🇵|东京|大阪|jp|japan)"
    icon: *icon_jp

  - !!merge <<: *proxy-groups_url-test_config
    name: 狮城自动
    filter: "(?i)(新加坡|坡|狮城|🇸🇬|sg|singapore)"
    icon: *icon_sg

  - !!merge <<: *proxy-groups_url-test_config
    name: 美国自动
    filter: "(?i)(美|🇺🇲|us|states|america|硅)"
    icon: *icon_us

  - !!merge <<: *proxy-groups_url-test_config
    filter: (?i)^(?!.*(?:🇭🇰|🇹🇼|🇯🇵|🇰🇷|🇺🇸|🇸🇬|🇨🇳|港|hk|hong|台|tw|taiwan|日本|jp|japan|韩|kr|korea|美|us|states|新加坡|sg|singapore|硅谷|硅))
    include-all: true
    name: 其他区域
    icon: *icon_amytelecom

  - !!merge <<: *proxy-groups_config
    name: 手动选择
    icon: *icon_static
    proxies:
      - 💚 全球直连
      - 其他区域

  - !!merge <<: *proxy-groups_config
    name: 默认
    icon: *icon_final
    proxies:
      - 💚 全球直连
      - 选择代理
rules:
  - GEOSITE,private,💚 全球直连
  - GEOSITE,bilibili,💚 全球直连
  - GEOSITE,spotify,香港自动
  - GEOSITE,github,香港自动
  - GEOSITE,microsoft,💚 全球直连
  - GEOSITE,speedtest,💚 全球直连
  - GEOSITE,meta,香港自动
  - GEOSITE,cloudflare,香港自动
  - GEOSITE,telegram,Telegram
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,apple,💚 全球直连
  - GEOSITE,geolocation-!cn@cn,💚 全球直连
  - GEOSITE,geolocation-!cn,选择代理
  - GEOSITE,geolocation-cn@!cn,选择代理
  - GEOSITE,geolocation-cn,💚 全球直连
  - GEOSITE,tld-cn,💚 全球直连
  - GEOIP,private,💚 全球直连
  - GEOIP,apple,💚 全球直连
  - GEOIP,telegram,Telegram
  - GEOIP,cloudflare,香港自动
  - GEOIP,google,Google
  - GEOIP,bilibili,💚 全球直连
  - GEOIP,cn,💚 全球直连
  - MATCH,默认