name: 自动化拉取规则
on:
  schedule:
    - cron: '0 1 * * *'    # UTC 1:00 = 北京时间 9:00
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  rule_sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rules:
          - name: 'a_dobe_dumb'
            url: 'https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/list.txt'
            format: 'list'
            processor: |
              sed -n -e '/# Last update:/p' -e '/^0\.0\.0\.0/s/0\.0\.0\.0 //p' "$TEMP_FILE" > "$PROCESSED_FILE"
              sed -i '1i\# 最后拉取时间' "$PROCESSED_FILE"

          - name: 'AWAvenue_Ads_Rule_Clash'
            url: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml'
            format: 'yaml'
            processor: |
              sed "1i\# 原始仓库: https://github.com/TG-Twilight/AWAvenue-Ads-Rule" "$TEMP_FILE" > "$PROCESSED_FILE"

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          repository: yangtudou/Script
          ref: main
          path: Script
          fetch-depth: 1

      - name: 处理规则文件
        env:
          TEMP_FILE: "temp_${{ matrix.rules.name }}"
          PROCESSED_FILE: "processed_${{ matrix.rules.name }}"
        run: |
          mkdir "$TEMP_FILE" "$PROCESSED_FILE"
          bash -c ls
          echo $PWD
          

      # - name: 提交变更
      #   run: |
      #     cd Script
      #     git add ruleProviders
          
      #     if [[ -n $(git status --porcelain ruleProviders) ]]; then
      #       git config --local user.email "action@github.com"
      #       git config --local user.name "GitHub Action"
      #       git commit -m "拉取新规则: ${{ join(matrix.rules.*) }} $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
      #       git push
      #       echo "➕ 变更已提交"
      #     else
      #       echo "🟢 无变更可提交"
      #     fi

  cleanup:
    runs-on: ubuntu-latest
    needs: rule_sync
    steps:
      - name: 清理工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_minimum_runs: 2
