name: 自动化拉取 MetaCubeX 规则
on:
  schedule:
    - cron: '0 1 * * *'    # UTC 1:00 = 北京时间 9:00
  workflow_dispatch: # 允许手动触发

# permissions:
#   contents: write
#   # actions: write

jobs:
  rule_sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
        with:
          path: rule_sync_temp  # 避免文件冲突

      - name: 检出 MetaCubeX/meta-rules-dat
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/meta-rules-dat
          ref: meta
          path: meta-rules-dat
          # token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 拉取规则文件
        run: |
          cp -f meta-rules-dat/geo/geosite/geolocation-!cn.yaml rule_sync_temp/ruleProviders/Stash/geolocation-!cn.yaml
      
      - name: Commit changes
        run: |
          cd rule_sync_temp
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "test Add public repo content"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用token推送


  # rule_sync:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       rules:
  #         - name: 'a_dobe_dumb'
  #           url: 'https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/list.txt'
  #           format: 'list'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed -n -e '/# Last update:/p' -e '/^0\.0\.0\.0/s/0\.0\.0\.0 //p' "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"

  #         - name: 'AWAvenue_Ads_Rule_Clash'
  #           url: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/TG-Twilight/AWAvenue-Ads-Rule" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
          
  #         - name: 'telegram_domain'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
 
  #         - name: 'telegram_ip'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"

  #         - name: 'google_domain'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
 
  #         - name: 'google_ip'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"

  #         - name: 'spotify_domain'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"

  #         - name: 'cn_domain'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
          
  #         - name: 'cn_ip'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
          
  #         - name: 'geolocation-!cn'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
          
  #         - name: 'youtube_domain'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
          
  #         - name: 'private_ip'
  #           url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml'
  #           format: 'yaml'
  #           processor: |
  #             CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
  #             sed "1i\# 原始仓库: https://github.com/MetaCubeX/meta-rules-dat/tree/meta/geo" "$TEMP_FILE" > "$PROCESSED_FILE"
  #             sed -i "1i\# 最后拉取时间: 北京时间 $CURRENT_TIME" "$PROCESSED_FILE"
  #     max-parallel: 1 # 每次只运行一个矩阵任务 
  #     fail-fast: false # 允许其他任失败也运行
  
  #   steps:
  #     - name: 检出仓库
  #       uses: actions/checkout@v4
  #       with:
  #         repository: yangtudou/Script
  #         path: rules_temp
  #         fetch-depth: 0

  #     - name: 处理规则文件
  #       env:
  #         TEMP_FILE: "temp_${{ matrix.rules.name }}"
  #         PROCESSED_FILE: "processed_${{ matrix.rules.name }}"
  #       run: |
  #         # 下载文件 保存为以 temp_ 为前缀的临时文件
  #         curl -fsSL -o "$TEMP_FILE" "${{ matrix.rules.url }}"

  #         # 执行处理器命令 并且更名为 processed_ 前缀的临时文件
  #         ${{ matrix.rules.processor }}

  #         # 移动最终文件 直接覆盖
  #         mv -f "$PROCESSED_FILE" "rules_temp/ruleProviders/Stash/${{ matrix.rules.name }}.${{ matrix.rules.format }}"
      
  #     - name: 提交变更
  #       run: |
  #         cd rules_temp/ruleProviders/Stash

  #         git config --local user.name "GitHub Action"
  #         git config --local user.email "action@github.com"

  #         if [[ $(git status --porcelain) ]]; then
  #           git pull
  #           git add ${{ matrix.rules.name }}.${{ matrix.rules.format }}
  #           git commit -m "拉取新规则: ${{ matrix.rules.name }} $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
  #           git push origin main
  #           echo "➕ 变更已提交"
  #         else
  #           echo "🟢 无变更可提交"
  #         fi